### ISSUE TITLE
谢谢！正是我寻找的一个好的转换工具，建议继续添加一些功能

### ISSUE THREAD

**Issue by stazeng** [Arman19941113/image-renamer#1]
比如：对没有exif信息的图片，可以自动移动到指定目录，或者按照它的建立日期进行转换。

再次感谢！

**Comment by Arman19941113** [comment]
> 比如：对没有exif信息的图片，可以自动移动到指定目录，或者按照它的建立日期进行转换。
> 
> 再次感谢！

支持将没有 exif 信息的文件自动移动到桌面 no-exif-dir 文件夹
